### ISSUE TITLE
请依据MIT开源协议保留汉化作者署名

### ISSUE THREAD

**Issue by ilworkcn** [vlssu/pterodactyl-chinese#1]
发现阁下分支仓库内使用了大量与我方仓库一致的汉化内容，我方严重怀疑阁下直接抄用了我方原创的大量汉化文本，且违反了我方开源仓库的MIT开源协议。请阁下遵循MIT开源协议恢复作者署名。

**Comment by vlssu** [comment]
是的，我确实引用了您的部分汉化文本
由于我在引用时是依据网页对照，导致个人疏忽，仓库中并未加上您的署名部分，现在我已经将之加上了，实在抱歉导致给您带来了困扰。

后续补充时间线：

- 我6月8日，看您还没更新，我就引用了当时现有汉化，，（当时后台还有很多没汉化），后面我自己汉化了用户列表、服务器列表 ，再到17日时我发现翼龙改了好多，21日时，因为我自己失误，导致仓库炸了，我就重新拉库再写了，导致现在的仓库没有了我自己部分汉化的记录（由于当时您还并未在源代码中署名，但最近您在源代码署名了，我没有注意到，实在抱歉但我现在已经加上了）
- 文中写的4小时，真的不是我特意删除您的署名（引用时还未有），是因为我将原本的仓库删了（翼龙改了好多，导致冲突文件也多），合并的时候把仓库搞炸了，我就重新拉取了仓库。
